---
# This file needs to be in the same directory as the interface code files!
#
# Align parameters
# path to singularity container for aligning speech with ready text.
align_container_name: "/scratch/project_2004354/containers/kaldi-aling_5.2-lahpuh.sif"

# path to singularity container for creating a transcript from speech.
rec_container_name: "/tmp/matthies/kaldi-rec-py2-1.0.sif"

# path to wrapper script for singularity containers. Used for adding slurm parameters.
singularity_wrapper: "/scratch/project_2004354/finnish-forced-alignment/wrappers/singularity_wrapper.sh"
